### ISSUE TITLE
Create Rancher catalogue

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-generic#2]
We should create a sibling repo to host the docker compose and the rancher compose templates for Rancher catalogue, similar to:

- [Kartoza](https://github.com/kartoza/kartoza-rancher-catalogue/)
- [Olivier Daland](https://github.com/PacificCommunity/rancher-catalogue)

**Comment by cezio** [comment]
Preliminary entry: https://github.com/cezio/geonode-generic/tree/master/templates/geonode-generic

**Comment by cezio** [comment]
Entry is in testing. Few notes:
* this entry is for one-host-one-stack scenario. For multiple stacks on one host, we'll need lb. It can be added manually to stack, or we can add dedicated entry for lb-enabled deployment
 * site should use dns entry, host should have port 80/tcp accessible
 * due to nature of containers, each deployment, restart or upgrade will use default fixtures, which will populate admin user. If we want to have customized credentials for admin, we should remove this fixture, and use other way to set up admin user

**Comment by giohappy** [comment]
Fixtures issues moved to a new specific issue #12
